// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class imageUrl2addedToAboutClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageUrl2addedToAboutClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202412262312172_imageUrl2-addedToAboutClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
